### ISSUE TITLE
Public suffix entries that start with "*." are not loaded the same way

### ISSUE THREAD

**Issue by skeets23** [layershifter/TLDDatabase#333]
While most of the entries in the public suffix list look like this:

```
// bb : https://en.wikipedia.org/wiki/.bb
bb
```

Some of them (for whatever reason) look like this:
```
// bd : https://en.wikipedia.org/wiki/.bd
*.bd
```

This seems more like an issue with the consistency of the public suffix list formatting, but it results in suffixes not being detected correctly:

```
$store = new Store();

$result = $store->isExists("bb");
$resultA = $store->isExists("bd");
$resultB = $store->isExists("*.bd");
```

In this case, `$result` and `$resultB` are `true`, and `$resultA` is `false`.

This causes TLDExtract to incorrectly parse domains that have suffixes with a `*.` prefix in the public suffix list. (there's actually quite a few, 66 of them)

**Comment by layershifter** [comment]
Hey, sorry for the late reply. I deprecated this package, please try https://github.com/jeremykendall/php-domain-parser it's more powerful, maintained and accurate 🔧
