### ISSUE TITLE
PSL update: Update list of .RU reserved domains (#359)

### ISSUE THREAD

**Issue by layershifter** [layershifter/TLDDatabase#85]
Update list of .RU reserved domains (#359)

See https://cctld.ru/en/domains/domens_ru/reserved/

Before September 2009, .RU had a list of reserved domains and

geographical domains.

https://cctld.ru/ru/docs/archive/detail.php?ELEMENT_ID=3446

At its meeting on 30 September 2009, the Council of the Coordination

Center for TLD .RU ruled to abolish special types of second-level domain

names in domain .RU.

As a result, several suffixes become open for registration. The issue

was originally tracked in publicsuffix/list#206 but since then we had

several different tickets, some of them requesting single removals:

- publicsuffix/list#206

- publicsuffix/list#344

- publicsuffix/list#345

- publicsuffix/list#340

- publicsuffix/list#338

- publicsuffix/list#206

- publicsuffix/list#43

- publicsuffix/list#44

**Comment by yaleks** [comment]
Actually this is a wrong commit, please revert.
Geographical domain names in Russia since 2009 handled by https://www.nic.ru/dns/service/en/geo.html (second and third level domain names) .

**Comment by layershifter** [comment]
@yaleks Yep, I see this, @adeepv has already made [publicsuffix/list/#377](https://github.com/publicsuffix/list/pull/377) for this issue, please make follow up there, this repo is only mirror of PSL database and some utils for it. After PR will be merged, I'll make release with it as soon as I can.

**Comment by layershifter** [comment]
As temporary solution I recommend to downgrade to `layershifter/tld-database@1.0.32` or use own database (see advanced usage section on README) 😕

**Comment by yaleks** [comment]
This is not a problem just for me. 
This DB is used by LetsEncrypt and I have no way to issue the certificate due to limits for "non-public" domains. 
So, please fix ASAP.
