### ISSUE TITLE
$store = new \LayerShifter\TLDDatabase\Update();

### ISSUE THREAD

**Issue by fpalamour** [layershifter/TLDDatabase#93]
Basic usage

First of all you need load Store class.

$store = new \LayerShifter\TLDDatabase\Update();

Isn't it supposed to be : 
$store = new \LayerShifter\TLDDatabase\Store(); ?

Am I missing something ?

**Comment by layershifter** [comment]
@fpalamour Thanks for your eyes :+1: Yes, of course it must be `$store = new \LayerShifter\TLDDatabase\Store();`

**Comment by layershifter** [comment]
Updated. Thanks again!

**Comment by fpalamour** [comment]
Glad I could help !
